[Main]
FileHead=D2800
RFileHead=E1000

CountBZ3=20
CountBZ1=20
Three=32
CountSV=900

UserPath1=D:\曹操传相关\复刻版6.6\
UserPath2=C:\Users\WH-DY\Desktop\新建文件夹\
UserPath3=C:\Users\WH-DY\Desktop\

UserBrowses=C:\Users\WH-DY\Desktop\新建文件夹\
UserBrowsel=D:\test

UserXK=A3280
BzXG=254 
SMagic=144
Xgh=72
FileType=0
ShowType=0
SCount=368
PY1=0
PY2=0
PY3=4384768

DefID=70 ;道具-防具起始序号，取值范围 0~255
AssID=109 ;道具-辅助起始序号，取值范围 0~255 

MarkCount=32

;---------------和策略扩展内容有关的地址-切勿修改------------------
;---------------------策略扩展数据在6.4+的地址---------------------
;目前策略总数为144个（含空白策略），数据全部扩充到了144，每个策略都有独立的数据


MgID=666992      ;4D1570 A2D70  策略效果索引
;此项平时一般不可擅自修改，仅在设置新开发的策略时修改

-----------------------------------------------------------------
MgAIYN1=667136   ;4D1600 A2E00  AI是否使用策略（战场）    13（0D）表示不使用
MgAIYN2=667280   ;4D1690 A2E90  AI和我军是否使用策略（练武场）  13（0D）表示不使用
;有些策略不适合在练武场使用，也应设为不可用，以免我军使用时出现bug（策略列表变灰）
;大多数新开发的策略AI都不会用，也没有写对应的AI代码，不要随意修改以免出现bug

-----------------------------------------------------------------
MgHit=667424     ;4D1720 A2F20  策略命中上限  
;一般来说设置的数据即为命中上限，但有几个特殊数字
;0 命中上限为90  （大觉醒）
;1 命中上限为100 （觉醒）
;2 命中上限为100 （低级五系，天气，补给 等）
;3 命中上限为34  （海啸）
;4 命中上限为50  （暗杀）
;-----------------------------------------------------------------
            
MgHurt=667712    ;4D1840 A3040  策略伤害系数
;一般来说设置的数据即为伤害系数，设置为28（1Ch）表示不伤血，有益策略也设为28
;有些无伤害的策略会把这个数据挪作它用，如召唤术
              
MgHurtYN=667856  ;4D18D0 A30D0  策略是否伤血  
;0 四系 
;1 毒麻  
;2 八图 撞心 
;3 青龙 朱雀
;4 不伤血  
;上面两条中 是否伤血 优先于 伤害系数，如果不伤血则伤害系数无效，但谍报例外

;-----------------------------------------------------------------          
MgMeff=668000    ;4D1960 A3160  小动画meff编号 
MgMcall=668144   ;4D19F0 A31F0  大动画mcall编号 
;如果大动画<100（64h）,则等于无效，只播放小动画；设为>=100 先播放Mcall，再播放小动画

;----------------------------------------------------------------- 
Mg8=667568       ;4D17B0 A2FB0 学会策略（8类设置）  

MgMF=666848      ;4D14E0 A2CE0  策略能否被模仿、辅助穿透对策略是否有效(新增属性)

;五灵珠脱胎于青龙，和青龙一样，总是单体穿透，这里的设置无效


; FileHead 是exe中S形象数据的位置，请勿修改
; RFileHead是exe中R形象数据的位置，请勿修改   
; UserPath是最后一次修改的文件所在目录
; UserXK是exe中兵种相克数据的位置，请勿修改
; CountBZ3三转兵种数 20个
; CountBZ1一转兵种数 20个
; SCount  放在Star里的装备数量
; SMagic  法术数量
; Threes  三转形象数量 32个
; CountSV  存档数量  如果自己增加了存档数，这里也可以改大
; BzXG    人物特效数量 143个（8F）
; 使用时务必注意exe版本，不可跨版本使用。
