[Main]
FileHead=D2800
RFileHead=E1000

CountBZ3=20
CountBZ1=20
Three=32
CountSV=900

UserPath1=F:\从0开始的AI制作曹操传MOD\曹操传加强版6.5（未加密）\基底\加强版6.5未加密版\
UserPath2=F:\从0开始的AI制作曹操传MOD\曹操传加强版6.5（未加密）\加强版6.5未加密版\RS\
UserPath3=C:\Users\WH-DY\Desktop\

UserBrowses=C:\Users\Mr.Wang\Desktop\新建文件夹 (2)\
UserBrowsel=D:\test

UserXK=A3280
BzXG=254 
SMagic=144
Xgh=72
FileType=0
ShowType=0
SCount=96
PY1=0
PY2=0
PY3=4384768

DefID=70 ;道具-防具起始序号，取值范围 0~255
AssID=109 ;道具-辅助起始序号，取值范围 0~255 


; FileHead 是exe中S形象数据的位置，请勿修改
; RFileHead是exe中R形象数据的位置，请勿修改   
; UserPath是最后一次修改的文件所在目录
; UserXK是exe中兵种相克数据的位置，请勿修改
; CountBZ3三转兵种数 20个
; CountBZ1一转兵种数 20个
; SCount  放在Star里的装备数量
; SMagic  法术数量
; Threes  三转形象数量 32个
; CountSV  存档数量  如果自己增加了存档数，这里也可以改大
; BzXG    人物特效数量 143个（8F）
; 使用时务必注意exe版本，不可跨版本使用。
