[Main]
FileHead=D2800
RFileHead=E1000

CountBZ3=20
CountBZ1=20
Three=32


UserPath=D:\Test\
UserXK=A3280

Xgh=72
FileType=0
ShowType=0
SCount=24
PY1=0
PY2=0
PY3=4384768

; FileHead 是exe中S形象数据的位置，请勿修改
; RFileHead是exe中R形象数据的位置，请勿修改   
; UserPath是最后一次修改的文件所在目录
; UserXK是exe中兵种相克数据的位置，请勿修改
; CountBZ3三转兵种数 20个
; CountBZ1一转兵种数 20个
; Threes  三转形象数量 32个
; 切勿用于5.7之前的exe。
