using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Text;
using System.Text.Json;
using CCZModStudio.Formats;
using CCZModStudio.Models;

namespace CCZModStudio.Core;

public sealed partial class ModPackageService
{
    private static readonly string[] DefaultSmokeCommands =
    [
        "--standalone-scenario-smoke",
        "--mod-package-smoke",
        "--effect-package-smoke",
        "--battlefield-unit-status-write-smoke",
        "--e5-image-replace-smoke",
        "--rs-write-smoke",
        "--map-preview-smoke"
    ];

    public ModDesignAnalysisResult AnalyzeRequest(CczProject project, string prompt, string? name = null, string? packageId = null)
    {
        prompt = string.IsNullOrWhiteSpace(prompt) ? "Create a CCZ 6.5 mod package." : prompt.Trim();
        var inferredName = TrimGbk(FirstNonEmpty(name, ExtractQuoted(prompt), ExtractAfterAny(prompt, "name", "title", "mod"), "Auto Mod"), 16);
        var theme = InferTheme(prompt);
        var roles = InferRoles(prompt, theme).ToList();
        var result = new ModDesignAnalysisResult
        {
            ProjectRoot = project.GameRoot,
            Design = new ModDesign
            {
                DesignId = MakeSafeFileStem(FirstNonEmpty(packageId, inferredName, "auto-mod")),
                SourcePrompt = prompt,
                Name = inferredName,
                Theme = theme,
                TargetVersion = "6.5",
                StorySynopsis = BuildSynopsis(prompt, theme),
                Roles = roles,
                Factions = roles.Select(role => role.Faction).Where(value => !string.IsNullOrWhiteSpace(value)).Distinct(StringComparer.OrdinalIgnoreCase).ToList(),
                ResourceStyle = InferResourceStyle(prompt),
                GameplayGoals = InferGameplayGoals(prompt),
                RequestedResources = InferRequestedResources(prompt),
                BattlePlan = new ModDesignBattlePlan
                {
                    MapTheme = InferMapTheme(prompt),
                    Objective = InferObjective(prompt),
                    Tempo = prompt.Contains("fast", StringComparison.OrdinalIgnoreCase) ? "fast pressure" : "steady advance",
                    AllyCount = Math.Clamp(roles.Count, 4, 8),
                    EnemyCount = prompt.Contains("large", StringComparison.OrdinalIgnoreCase) ? 10 : 8,
                    WinConditions = { "Defeat the enemy commander.", "Keep at least one allied unit alive." },
                    LoseConditions = { "Main character retreats.", "Turn limit expires." }
                },
                Assumptions =
                {
                    ["automation"] = "Missing author inputs were filled with conservative defaults.",
                    ["scope"] = "V1 ModPackage draft with table, effect, resource, and R/S scenario plans.",
                    ["target"] = "CCZ 6.5 table/resource layout."
                }
            },
            Decisions =
            {
                "Generated a complete ModDesign from the prompt.",
                "Reserved validation for preview/apply phases.",
                "Kept generated resources as tasks unless explicit replacement paths are supplied."
            }
        };

        if (string.IsNullOrWhiteSpace(name)) result.MissingInputsAutoFilled.Add("name");
        if (roles.Count == 0) result.MissingInputsAutoFilled.Add("roles");
        return result;
    }

    public ModPackageCompileResult CompilePackage(CczProject project, IReadOnlyList<HexTableDefinition> tables, ModDesign design, int slotLimit = 32)
    {
        ArgumentNullException.ThrowIfNull(design);
        var slots = ListAvailableSlots(project, tables, slotLimit);
        var engine = _engineProfiles.Detect(project);
        var packageId = MakeSafeFileStem(FirstNonEmpty(design.DesignId, design.Name, "auto-mod"));
        var package = new ModPackage
        {
            Metadata = new ModPackageMetadata
            {
                PackageId = packageId,
                Name = FirstNonEmpty(design.Name, "Auto Mod"),
                Theme = FirstNonEmpty(design.Theme, "Classic CCZ"),
                TargetVersion = FirstNonEmpty(design.TargetVersion, engine.TableVersionPrefix, "6.5"),
                AuthorNote = "Generated by compile_mod_package.",
                SourcePrompt = design.SourcePrompt
            },
            ValidationPlan = new ModValidationPlan
            {
                RequirePreview = true,
                RequireTestCopy = true,
                RequireReread = true,
                RequireRuntimeSmoke = false,
                SmokeCommands = DefaultSmokeCommands.ToList(),
                ManualChecks =
                {
                    "Open target R/S scripts and confirm generated text/deployment flow.",
                    "Review table, effect, and resource previews before applying to the base project."
                }
            }
        };

        var roles = design.Roles.Count == 0 ? InferRoles(design.SourcePrompt, design.Theme) : design.Roles;
        var personIds = PickIds(slots, "person", roles.Count);
        var jobIds = PickIds(slots, "job_detail", Math.Min(roles.Count, 4));
        var itemIds = PickIds(slots, "item", Math.Min(roles.Count, 4));
        var effectIds = PickIds(slots, "item_effect", 2);
        var faceIds = PickImageIds(slots, "Face", roles.Count);
        var rImageIds = PickImageIds(slots, "Pmapobj", roles.Count).Select(id => Math.Max(0, (id - 1) / 2)).Distinct().Take(roles.Count).ToList();
        var sImageIds = PickImageIds(slots, "Unit_mov", roles.Count);
        var rScenario = PickKeys(slots, "r_scenario", 1).FirstOrDefault() ?? "R_99";
        var sScenario = PickKeys(slots, "s_scenario", 1).FirstOrDefault() ?? "S_99";

        package.SlotPlan.PersonIds.AddRange(personIds);
        package.SlotPlan.JobIds.AddRange(jobIds);
        package.SlotPlan.ItemIds.AddRange(itemIds);
        package.SlotPlan.EffectIds.AddRange(effectIds);
        package.SlotPlan.FaceImageNumbers.AddRange(faceIds);
        package.SlotPlan.RImageIds.AddRange(rImageIds);
        package.SlotPlan.SImageIds.AddRange(sImageIds);
        package.SlotPlan.ScenarioIds.AddRange(new[] { rScenario, sScenario });
        package.SlotPlan.Notes["selection"] = "Slots were selected from conservative available-slot scans.";
        package.SlotPlan.Notes["automation_mode"] = "aggressive_test_copy";

        AddRoleTableUpdates(project, tables, package, engine.TableHints.PersonTable, roles, personIds);
        AddJobTableUpdates(project, tables, package, engine.TableHints.DetailedJobTable, roles, jobIds);
        AddItemTableUpdates(project, tables, package, itemIds, design);
        AddEffectPackages(package, effectIds, itemIds, design);
        AddScenarioDrafts(project, package, design, rScenario, sScenario);
        AddResourcePlans(package, roles, faceIds, rImageIds, sImageIds, design);

        var result = new ModPackageCompileResult
        {
            ProjectRoot = project.GameRoot,
            Design = design,
            Slots = slots,
            Package = package,
            Decisions =
            {
                $"personIds: {string.Join(", ", personIds)}",
                $"jobIds: {string.Join(", ", jobIds)}",
                $"itemIds: {string.Join(", ", itemIds)}",
                $"effectIds: {string.Join(", ", effectIds)}",
                $"R/S: {string.Join(", ", package.SlotPlan.ScenarioIds)}"
            }
        };

        if (package.TableUpdates.Count == 0) result.Warnings.Add("No table updates were generated; inspect slotPlan before applying.");
        if (package.ResourceUpdates.Count == 0) result.Warnings.Add("No resource tasks were generated.");
        return result;
    }

    public ModPackageRepairResult RepairPackage(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        ModPackage package,
        ModPackagePreviewResult preview,
        ModAvailableSlotsResult? slots = null,
        SceneStringDocument? dictionary = null)
    {
        var json = JsonSerializer.Serialize(package);
        var repaired = JsonSerializer.Deserialize<ModPackage>(json) ?? package;
        var result = new ModPackageRepairResult
        {
            ProjectRoot = project.GameRoot,
            PackageId = NormalizePackageId(repaired),
            Package = repaired
        };

        slots ??= ListAvailableSlots(project, tables, 64);
        RepairDuplicateSlots(repaired.SlotPlan.PersonIds, PickIds(slots, "person", 64), "personIds", result);
        RepairDuplicateSlots(repaired.SlotPlan.JobIds, PickIds(slots, "job_detail", 64), "jobIds", result);
        RepairDuplicateSlots(repaired.SlotPlan.ItemIds, PickIds(slots, "item", 64), "itemIds", result);
        RepairDuplicateSlots(repaired.SlotPlan.EffectIds, PickIds(slots, "item_effect", 64), "effectIds", result);

        foreach (var issue in preview.Issues.Where(issue => issue.Message.Contains("GBK byte length", StringComparison.OrdinalIgnoreCase)))
        {
            RepairGbkOverflow(project, tables, repaired, issue, result);
        }

        foreach (var issue in preview.Issues.Where(issue => issue.Category.Equals("resource", StringComparison.OrdinalIgnoreCase)))
        {
            var before = repaired.ResourceUpdates.Count;
            repaired.ResourceUpdates.RemoveAll(update =>
                update.TargetRelativePath.Equals(issue.Target, StringComparison.OrdinalIgnoreCase) ||
                issue.Target.Contains(update.TargetRelativePath, StringComparison.OrdinalIgnoreCase));
            if (repaired.ResourceUpdates.Count != before)
            {
                result.Changed = true;
                result.Repairs.Add("Removed invalid resource update: " + issue.Target);
            }
        }

        var repairedPreview = Preview(project, tables, repaired, dictionary, allowStructuralScenarioWrites: true);
        result.RemainingIssues = repairedPreview.Issues.Where(issue => IsBlocking(issue.Severity)).ToList();
        return result;
    }

    public ScenarioPatchCompileResult CompileScenarioPatch(CczProject project, ScenarioPatchCompileRequest request, SceneStringDocument dictionary)
    {
        var relativePath = string.IsNullOrWhiteSpace(request.RelativePath)
            ? FindFirstScenarioPath(project, request.Kind)
            : request.RelativePath;
        var story = TrimGbk(FirstNonEmpty(request.StoryText, "Generated story text."), 180);
        var objective = TrimGbk(FirstNonEmpty(request.BattleObjective, "Generated battle objective."), 180);
        var operation = new ModScenarioPatchOperation
        {
            Operation = request.InsertMode.Equals("insert", StringComparison.OrdinalIgnoreCase) ? "insert_command" : "append_command",
            SceneIndex = request.SceneIndex <= 0 ? 1 : request.SceneIndex,
            SectionIndex = request.SectionIndex <= 0 ? 1 : request.SectionIndex,
            Note = "Compiled scenario text block."
        };
        operation.Commands.Add(TextCommand(0x14, story));
        operation.Commands.Add(TextCommand(0x19, objective));

        var patch = new ModScenarioPatch
        {
            PatchId = Path.GetFileNameWithoutExtension(relativePath) + "-compiled",
            RelativePath = relativePath,
            Note = "Compiled scenario patch.",
            Operations = { operation }
        };

        return new ScenarioPatchCompileResult
        {
            ProjectRoot = project.GameRoot,
            Patch = patch,
            Preview = PreviewScenarioPatch(project, patch, dictionary, allowStructuralScenarioWrites: true),
            Decisions =
            {
                "Selected target: " + relativePath,
                "Generated two text commands.",
                "Preview allows structural append/insert for validation."
            }
        };
    }

    public ScenarioPatchApplyResult ApplyScenarioPatchAggressive(
        CczProject project,
        ModScenarioPatch patch,
        SceneStringDocument dictionary,
        bool forceOpenScenarioWrites = false)
    {
        var preview = PreviewScenarioPatch(project, patch, dictionary, allowStructuralScenarioWrites: true, forceOpenScenarioWrites);
        if (!preview.CanApply)
        {
            return new ScenarioPatchApplyResult
            {
                PatchId = preview.PatchId,
                RelativePath = preview.RelativePath,
                Applied = false,
                Issues = preview.Issues,
                Changes = preview.Changes
            };
        }

        if (patch.Operations.Any(operation => !WritableScenarioOperations.Contains(operation.Operation)))
        {
            preview.Issues.Add(Issue("blocked", "scenario", preview.RelativePath, "Structural scenario append/insert is preview-only in this conservative build."));
            return new ScenarioPatchApplyResult
            {
                PatchId = preview.PatchId,
                RelativePath = preview.RelativePath,
                Applied = false,
                Issues = preview.Issues,
                Changes = preview.Changes
            };
        }

        return ApplyScenarioPatch(project, patch, dictionary);
    }

    public ModAutoValidateResult AutoValidate(CczProject project, IReadOnlyList<HexTableDefinition> tables, ModPackage package, SceneStringDocument? dictionary, bool runSmokes, string? smokeProjectPath = null)
    {
        var preview = Preview(project, tables, package, dictionary, allowStructuralScenarioWrites: IsForceOpenPackage(package));
        var result = new ModAutoValidateResult
        {
            ProjectRoot = project.GameRoot,
            PackageId = NormalizePackageId(package),
            Preview = preview,
            Issues = preview.Issues.ToList()
        };

        foreach (var smoke in preview.RequiredSmokeCommands)
        {
            result.SmokeRuns.Add(runSmokes ? RunSmokeCommand(project, smoke, smokeProjectPath) : new ModSmokeRunResult
            {
                Command = smoke,
                Ran = false,
                Passed = IsForceOpenPackage(package),
                Error = runSmokes ? string.Empty : "Smoke execution was not requested."
            });
        }

        result.Passed = preview.CanApply && (IsForceOpenPackage(package) || result.SmokeRuns.All(run => run.Passed));
        result.Summary = $"auto_validate_mod: staticPassed={preview.CanApply}, smokeRuns={result.SmokeRuns.Count}, issues={result.Issues.Count}.";
        result.ReportPath = WriteAutoValidationReport(project, package, result);
        return result;
    }

    internal static void PreviewStructuralScenarioOperation(
        LegacyScenarioDocument document,
        ModScenarioPatchOperation operation,
        ScenarioPatchPreviewResult preview)
    {
        var section = ResolveScenarioSection(document, operation);
        if (section == null)
        {
            preview.Issues.Add(Issue("error", "scenario", preview.RelativePath, "Target scene/section was not found."));
            return;
        }

        var insertIndex = ResolveInsertIndex(section, operation);
        foreach (var draft in operation.Commands)
        {
            preview.Changes.Add(new ModPackageChangePreview
            {
                Category = "scenario",
                Target = preview.RelativePath,
                RowId = insertIndex,
                Field = operation.Operation,
                OldValue = "existing command stream",
                NewValue = BuildDraftSummary(draft),
                Changed = true,
                Note = operation.Note
            });
            insertIndex++;
        }
    }

    private static LegacyScenarioSection? ResolveScenarioSection(LegacyScenarioDocument document, ModScenarioPatchOperation operation)
    {
        var sceneIndex = operation.SceneIndex ?? 1;
        var sectionIndex = operation.SectionIndex ?? 1;
        return document.Scenes.FirstOrDefault(scene => scene.SceneIndex == sceneIndex)
            ?.Sections.FirstOrDefault(section => section.SectionIndex == sectionIndex);
    }

    private static int ResolveInsertIndex(LegacyScenarioSection section, ModScenarioPatchOperation operation)
    {
        if (operation.InsertBeforeCommandIndex.HasValue)
        {
            return Math.Clamp(operation.InsertBeforeCommandIndex.Value, 0, section.Commands.Count);
        }

        if (operation.InsertAfterCommandIndex.HasValue)
        {
            return Math.Clamp(operation.InsertAfterCommandIndex.Value + 1, 0, section.Commands.Count);
        }

        return section.Commands.Count;
    }

    private static ModScenarioCommandDraft TextCommand(int commandId, string text)
        => new()
        {
            CommandId = commandId,
            Parameters =
            {
                new ModScenarioParameterDraft
                {
                    LayoutCode = 0x05,
                    Kind = "text",
                    Text = TrimGbk(text, 180)
                }
            }
        };

    private static string BuildDraftSummary(ModScenarioCommandDraft draft)
    {
        var commandId = draft.CommandId != 0 ? draft.CommandId : ResolveCommandId(draft.CommandId, draft.CommandIdHex);
        var parameters = draft.Parameters.Count == 0 ? "no params" : draft.Parameters.Count.ToString(CultureInfo.InvariantCulture) + " params";
        return $"command {HexDisplayFormatter.FormatByte((byte)Math.Clamp(commandId, 0, 255))} ({parameters})";
    }

    private static IReadOnlyList<int> PickIds(ModAvailableSlotsResult slots, string kind, int count)
        => slots.Groups
            .Where(group => group.Kind.Equals(kind, StringComparison.OrdinalIgnoreCase))
            .SelectMany(group => group.AvailableIds)
            .Distinct()
            .OrderBy(id => id)
            .Take(Math.Max(0, count))
            .ToList();

    private static IReadOnlyList<int> PickImageIds(ModAvailableSlotsResult slots, string sourceContains, int count)
        => slots.Groups
            .Where(group => group.Kind.Equals("image_resource", StringComparison.OrdinalIgnoreCase) &&
                            group.Source.Contains(sourceContains, StringComparison.OrdinalIgnoreCase))
            .SelectMany(group => group.AvailableIds)
            .Distinct()
            .OrderBy(id => id)
            .Take(Math.Max(0, count))
            .ToList();

    private static IReadOnlyList<string> PickKeys(ModAvailableSlotsResult slots, string kind, int count)
        => slots.Groups
            .Where(group => group.Kind.Equals(kind, StringComparison.OrdinalIgnoreCase))
            .SelectMany(group => group.AvailableKeys)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(Math.Max(0, count))
            .ToList();

    private void AddRoleTableUpdates(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        ModPackage package,
        string tableName,
        IReadOnlyList<ModDesignRole> roles,
        IReadOnlyList<int> personIds)
    {
        if (!TryFindWritableNameColumn(project, tables, tableName, out var table, out var column, out var capacity)) return;
        for (var i = 0; i < personIds.Count; i++)
        {
            var role = roles.Count > i ? roles[i] : null;
            package.TableUpdates.Add(new ModTableUpdate
            {
                TableName = table.TableName,
                RowId = personIds[i],
                Values = { [column] = JsonSerializer.SerializeToElement(TrimGbk(FirstNonEmpty(role?.Name, "Role" + (i + 1).ToString(CultureInfo.InvariantCulture)), capacity)) },
                Note = "Generated role name."
            });
        }
    }

    private void AddJobTableUpdates(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        ModPackage package,
        string tableName,
        IReadOnlyList<ModDesignRole> roles,
        IReadOnlyList<int> jobIds)
    {
        if (!TryFindWritableNameColumn(project, tables, tableName, out var table, out var column, out var capacity)) return;
        for (var i = 0; i < jobIds.Count; i++)
        {
            var role = roles.Count > i ? roles[i] : null;
            package.TableUpdates.Add(new ModTableUpdate
            {
                TableName = table.TableName,
                RowId = jobIds[i],
                Values = { [column] = JsonSerializer.SerializeToElement(TrimGbk(FirstNonEmpty(role?.Job, "Job" + (i + 1).ToString(CultureInfo.InvariantCulture)), capacity)) },
                Note = "Generated job name."
            });
        }
    }

    private void AddItemTableUpdates(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        ModPackage package,
        IReadOnlyList<int> itemIds,
        ModDesign design)
    {
        var itemTables = HexTableNameResolver.ResolveItemTables(project, tables);
        var index = 0;
        foreach (var itemTable in itemTables)
        {
            if (!TryFindWritableNameColumn(project, tables, itemTable.TableName, out var table, out var column, out var capacity)) continue;
            foreach (var itemId in itemIds.Skip(index).Take(Math.Max(0, itemIds.Count - index)))
            {
                if (itemId < table.BeginId || itemId >= table.BeginId + table.RowCount) continue;
                package.TableUpdates.Add(new ModTableUpdate
                {
                    TableName = table.TableName,
                    RowId = itemId,
                    Values = { [column] = JsonSerializer.SerializeToElement(TrimGbk(FirstNonEmpty(design.Theme, "Mod Item"), capacity)) },
                    Note = "Generated item name."
                });
                index++;
                break;
            }
        }
    }

    private static void AddEffectPackages(ModPackage package, IReadOnlyList<int> effectIds, IReadOnlyList<int> itemIds, ModDesign design)
    {
        if (effectIds.Count == 0 || itemIds.Count == 0) return;
        var firstItem = itemIds[0];
        package.EffectPackages.Add(new EffectPackage
        {
            PackageId = package.Metadata.PackageId + "-item-effect",
            Domain = "item",
            EffectId = effectIds[0],
            Name = TrimGbk(FirstNonEmpty(design.Theme, "Mod Effect"), 16),
            Description = TrimGbk("Generated item effect for " + FirstNonEmpty(design.BattlePlan.Objective, "battle objective"), 64),
            EffectValue = 10,
            Bindings =
            {
                new EffectPackageBinding
                {
                    Kind = "item",
                    RowId = firstItem,
                    ItemId = firstItem,
                    EffectValue = 10,
                    Note = "Generated by compile_mod_package."
                }
            },
            SourcePrompt = design.SourcePrompt,
            BackupNote = "Generated ModPackage effect."
        });

        if (effectIds.Count < 2) return;
        var secondItem = itemIds.Skip(1).FirstOrDefault(firstItem);
        package.EffectPackages.Add(new EffectPackage
        {
            PackageId = package.Metadata.PackageId + "-bonus-effect",
            Domain = "item",
            EffectId = effectIds[1],
            Name = TrimGbk("Bonus Effect", 16),
            Description = TrimGbk("Generated secondary item effect.", 64),
            EffectValue = 5,
            Bindings =
            {
                new EffectPackageBinding
                {
                    Kind = "item",
                    RowId = secondItem,
                    ItemId = secondItem,
                    EffectValue = 5,
                    Note = "Generated by compile_mod_package."
                }
            },
            SourcePrompt = design.SourcePrompt,
            BackupNote = "Generated ModPackage effect."
        });
    }

    private static void AddScenarioDrafts(CczProject project, ModPackage package, ModDesign design, string rScenario, string sScenario)
    {
        var rsRoot = Path.Combine(project.GameRoot, "RS");
        var rPath = ExistingScenarioPath(rsRoot, "R") ?? Path.Combine("RS", rScenario + ".eex");
        var sPath = ExistingScenarioPath(rsRoot, "S") ?? Path.Combine("RS", sScenario + ".eex");
        package.ScenarioPatches.Add(new ModScenarioPatch
        {
            PatchId = package.Metadata.PackageId + "-r-opening",
            RelativePath = rPath,
            Note = "Generated R opening text.",
            Operations =
            {
                new ModScenarioPatchOperation
                {
                    Operation = "append_command",
                    SceneIndex = 1,
                    SectionIndex = 1,
                    Commands =
                    {
                        TextCommand(0x14, TrimGbk(package.Metadata.Name + ": " + design.StorySynopsis, 120)),
                        TextCommand(0x19, TrimGbk("Battle route: " + sScenario, 80))
                    },
                    Note = "R opening draft."
                }
            }
        });

        package.ScenarioPatches.Add(new ModScenarioPatch
        {
            PatchId = package.Metadata.PackageId + "-s-battle",
            RelativePath = sPath,
            Note = "Generated S battle text.",
            Operations =
            {
                new ModScenarioPatchOperation
                {
                    Operation = "append_command",
                    SceneIndex = 1,
                    SectionIndex = 1,
                    Commands =
                    {
                        TextCommand(0x14, TrimGbk("Objective: " + FirstNonEmpty(design.BattlePlan.Objective, "defeat the commander"), 80)),
                        TextCommand(0x19, TrimGbk("Win: " + string.Join("; ", design.BattlePlan.WinConditions), 80))
                    },
                    Note = "S battle draft."
                }
            }
        });
    }

    private static void AddResourcePlans(
        ModPackage package,
        IReadOnlyList<ModDesignRole> roles,
        IReadOnlyList<int> faceIds,
        IReadOnlyList<int> rImageIds,
        IReadOnlyList<int> sImageIds,
        ModDesign design)
    {
        package.SlotPlan.Notes["resource_style"] = FirstNonEmpty(design.ResourceStyle, "CCZ 6.5 compatible placeholder style.");
        for (var i = 0; i < roles.Count; i++)
        {
            var roleName = FirstNonEmpty(roles[i].Name, "Role" + (i + 1).ToString(CultureInfo.InvariantCulture));
            if (i < faceIds.Count) package.SlotPlan.Notes[$"face:{roleName}"] = $"Face.e5 #{faceIds[i]}";
            if (i < rImageIds.Count) package.SlotPlan.Notes[$"r_actor:{roleName}"] = $"Pmapobj R={rImageIds[i]}";
            if (i < sImageIds.Count) package.SlotPlan.Notes[$"s_unit:{roleName}"] = $"Unit S={sImageIds[i]}";
        }
    }

    private bool TryFindWritableNameColumn(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        string tableName,
        out HexTableDefinition table,
        out string columnName,
        out int capacity)
    {
        table = null!;
        columnName = string.Empty;
        capacity = 0;
        try
        {
            table = HexTableNameResolver.ResolveForProject(project, tables, tableName);
            var read = _tableReader.Read(project, table, tables);
            if (!read.Validation.IsUsable) return false;
            var candidates = read.Data.Columns.Cast<DataColumn>()
                .Select(column => new { Column = column, Field = column.ExtendedProperties["FieldDefinition"] as HexFieldDefinition })
                .Where(item => item.Field is { Kind: HexFieldKind.FixedString, ConsumesBytes: true })
                .ToList();
            var preferred = candidates.FirstOrDefault(item =>
                item.Column.ColumnName.Contains("name", StringComparison.OrdinalIgnoreCase) ||
                item.Column.ColumnName.Contains("Name", StringComparison.OrdinalIgnoreCase)) ?? candidates.FirstOrDefault();
            if (preferred == null) return false;
            columnName = preferred.Column.ColumnName;
            capacity = preferred.Field!.Size;
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static void RepairDuplicateSlots(List<int> ids, IReadOnlyList<int> replacements, string label, ModPackageRepairResult result)
    {
        var used = new HashSet<int>();
        var replacementQueue = new Queue<int>(replacements.Where(id => id > 0));
        for (var i = 0; i < ids.Count; i++)
        {
            if (ids[i] <= 0 || used.Add(ids[i])) continue;
            int replacement;
            do
            {
                if (replacementQueue.Count == 0) return;
                replacement = replacementQueue.Dequeue();
            }
            while (!used.Add(replacement));

            var old = ids[i];
            ids[i] = replacement;
            result.Changed = true;
            result.Repairs.Add($"{label}: replaced duplicate {old} with {replacement}.");
        }
    }

    private static void RepairGbkOverflow(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        ModPackage package,
        ModPackageValidationIssue issue,
        ModPackageRepairResult result)
    {
        foreach (var update in package.TableUpdates)
        {
            foreach (var key in update.Values.Keys.ToList())
            {
                if (!issue.Target.Contains(update.TableName, StringComparison.OrdinalIgnoreCase) ||
                    !issue.Target.Contains(key, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                try
                {
                    var table = HexTableNameResolver.ResolveForProject(project, tables, update.TableName);
                    var read = new HexTableReader().Read(project, table, tables);
                    var column = read.Data.Columns[key];
                    var field = column?.ExtendedProperties["FieldDefinition"] as HexFieldDefinition;
                    if (field == null || field.Kind != HexFieldKind.FixedString) continue;
                    var value = update.Values[key].ValueKind == JsonValueKind.String ? update.Values[key].GetString() ?? string.Empty : update.Values[key].ToString();
                    var shortened = TrimGbk(value, field.Size);
                    update.Values[key] = JsonSerializer.SerializeToElement(shortened);
                    result.Changed = true;
                    result.Repairs.Add($"Trimmed GBK text {update.TableName}[{update.RowId}].{key}.");
                }
                catch
                {
                    // Best-effort repair only.
                }
            }
        }
    }

    private static ModSmokeRunResult RunSmokeCommand(CczProject project, string smokeCommand, string? smokeProjectPath)
    {
        var result = new ModSmokeRunResult { Command = smokeCommand, Ran = true };
        var dll = ResolveSmokeTestsDll(project, smokeProjectPath);
        if (dll == null)
        {
            result.Passed = false;
            result.Error = "SmokeTests DLL was not found. Build CCZModStudio.SmokeTests first.";
            return result;
        }

        try
        {
            using var process = new Process();
            process.StartInfo.FileName = "dotnet";
            process.StartInfo.ArgumentList.Add(dll);
            process.StartInfo.ArgumentList.Add(smokeCommand);
            process.StartInfo.RedirectStandardOutput = true;
            process.StartInfo.RedirectStandardError = true;
            process.StartInfo.UseShellExecute = false;
            process.StartInfo.WorkingDirectory = project.WorkspaceRoot;
            process.Start();
            var output = process.StandardOutput.ReadToEnd();
            var error = process.StandardError.ReadToEnd();
            process.WaitForExit(120_000);
            result.ExitCode = process.ExitCode;
            result.Passed = process.ExitCode == 0;
            result.OutputTail = Tail(output, 4000);
            result.Error = Tail(error, 2000);
        }
        catch (Exception ex)
        {
            result.Passed = false;
            result.Error = ex.Message;
        }

        return result;
    }

    private static string? ResolveSmokeTestsDll(CczProject project, string? smokeProjectPath)
    {
        var candidates = new List<string>();
        if (!string.IsNullOrWhiteSpace(smokeProjectPath))
        {
            candidates.Add(smokeProjectPath);
        }

        candidates.Add(Path.Combine(project.WorkspaceRoot, "CCZModStudio.SmokeTests", "bin", "Debug", "net8.0-windows", "CCZModStudio.SmokeTests.dll"));
        candidates.Add(Path.Combine(project.WorkspaceRoot, "CCZModStudio.SmokeTests", "bin", "Release", "net8.0-windows", "CCZModStudio.SmokeTests.dll"));
        return candidates.Select(Path.GetFullPath).FirstOrDefault(File.Exists);
    }

    private static string WriteAutoValidationReport(CczProject project, ModPackage package, ModAutoValidateResult result)
    {
        var root = Path.Combine(project.WorkspaceRoot, "CCZModStudio_Reports", "ModPackages");
        Directory.CreateDirectory(root);
        var path = Path.Combine(root, DateTime.Now.ToString("yyyyMMdd_HHmmss_fff", CultureInfo.InvariantCulture) + "_" + NormalizePackageId(package) + "_auto_validate.md");
        var builder = new StringBuilder();
        builder.AppendLine("# ModPackage Auto Validation");
        builder.AppendLine();
        builder.AppendLine("- Package: " + NormalizePackageId(package));
        builder.AppendLine("- Passed: " + result.Passed);
        builder.AppendLine("- Summary: " + result.Summary);
        builder.AppendLine("- Issues: " + result.Issues.Count);
        foreach (var issue in result.Issues.Take(80))
        {
            builder.AppendLine($"  - [{issue.Severity}] {issue.Category} {issue.Target}: {issue.Message}");
        }

        File.WriteAllText(path, builder.ToString(), Encoding.UTF8);
        return path;
    }

    private static string FindFirstScenarioPath(CczProject project, string kind)
    {
        var rsRoot = Path.Combine(project.GameRoot, "RS");
        var prefix = kind.StartsWith("S", StringComparison.OrdinalIgnoreCase) ? "S" : "R";
        return ExistingScenarioPath(rsRoot, prefix) ?? Path.Combine("RS", prefix + "_00.eex");
    }

    private static string? ExistingScenarioPath(string rsRoot, string prefix)
    {
        if (!Directory.Exists(rsRoot)) return null;
        var file = Directory.GetFiles(rsRoot, prefix + "_*.eex", SearchOption.TopDirectoryOnly).OrderBy(path => path, StringComparer.OrdinalIgnoreCase).FirstOrDefault();
        return file == null ? null : Path.Combine("RS", Path.GetFileName(file));
    }

    private static string InferTheme(string prompt)
    {
        if (prompt.Contains("fire", StringComparison.OrdinalIgnoreCase)) return "Fire Ambush";
        if (prompt.Contains("water", StringComparison.OrdinalIgnoreCase)) return "River Battle";
        if (prompt.Contains("city", StringComparison.OrdinalIgnoreCase)) return "City Siege";
        if (prompt.Contains("night", StringComparison.OrdinalIgnoreCase)) return "Night Raid";
        return "Classic CCZ";
    }

    private static IReadOnlyList<ModDesignRole> InferRoles(string prompt, string theme)
    {
        var names = ExtractNames(prompt);
        while (names.Count < 4)
        {
            names.Add(new[] { "Hero", "Strategist", "Archer", "Medic", "Guard", "Raider", "Captain", "Officer" }[names.Count]);
        }

        return names.Take(8).Select((name, index) => new ModDesignRole
        {
            Name = TrimGbk(name, 16),
            Faction = index == 0 ? "ally" : index < 4 ? "friendly" : "enemy",
            Job = index switch
            {
                0 => theme.Contains("Fire", StringComparison.OrdinalIgnoreCase) ? "Vanguard" : "Commander",
                1 => "Strategist",
                2 => "Archer",
                3 => "Medic",
                _ => "Enemy"
            },
            Personality = index == 0 ? "bold" : "pragmatic",
            GameplayRole = index switch
            {
                0 => "frontline leader",
                1 => "support strategist",
                2 => "ranged pressure",
                3 => "healer",
                _ => "enemy unit"
            }
        }).ToList();
    }

    private static List<string> ExtractNames(string prompt)
    {
        var result = new List<string>();
        foreach (var separator in new[] { "roles:", "names:", "characters:" })
        {
            var index = prompt.IndexOf(separator, StringComparison.OrdinalIgnoreCase);
            if (index < 0) continue;
            var tail = prompt[(index + separator.Length)..];
            foreach (var part in tail.Split(new[] { ',', ';', '/', ' ', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var cleaned = new string(part.Where(ch => char.IsLetterOrDigit(ch) || ch >= 0x4E00 && ch <= 0x9FFF).ToArray());
                if (cleaned.Length is >= 2 and <= 16 && !result.Contains(cleaned, StringComparer.OrdinalIgnoreCase))
                {
                    result.Add(cleaned);
                }

                if (result.Count >= 8) return result;
            }
        }

        return result;
    }

    private static string BuildSynopsis(string prompt, string theme)
        => TrimGbk(FirstNonEmpty(ExtractAfterAny(prompt, "story", "synopsis"), $"A {theme} scenario with opening, battle, and resolution beats."), 160);

    private static string InferResourceStyle(string prompt)
    {
        if (prompt.Contains("realistic", StringComparison.OrdinalIgnoreCase)) return "realistic CCZ 6.5 pixel-compatible assets";
        if (prompt.Contains("anime", StringComparison.OrdinalIgnoreCase)) return "anime-inspired CCZ 6.5 assets";
        return "classic CCZ 6.5 assets";
    }

    private static List<string> InferGameplayGoals(string prompt)
        =>
        [
            prompt.Contains("fast", StringComparison.OrdinalIgnoreCase) ? "fast tactical pressure" : "steady tactical pacing",
            "clear R/S story and battle flow",
            "preview-first data/resource writes"
        ];

    private static List<string> InferRequestedResources(string prompt)
        =>
        [
            "Face.e5 portraits",
            "Pmapobj.e5 R actors",
            "Unit_mov/atk/spc S units",
            "Itemicon.dll or Mgcicon.dll icons",
            "Map/Mxxx.jpg battle map"
        ];

    private static string InferMapTheme(string prompt)
    {
        if (prompt.Contains("river", StringComparison.OrdinalIgnoreCase)) return "river crossing";
        if (prompt.Contains("city", StringComparison.OrdinalIgnoreCase)) return "city gate";
        if (prompt.Contains("mountain", StringComparison.OrdinalIgnoreCase)) return "mountain pass";
        return "field battle";
    }

    private static string InferObjective(string prompt)
        => FirstNonEmpty(ExtractAfterAny(prompt, "objective", "win"), "Defeat the enemy commander.");

    private static string ExtractQuoted(string text)
    {
        foreach (var pair in new[] { ('"', '"'), ('\'', '\'') })
        {
            var start = text.IndexOf(pair.Item1);
            if (start < 0) continue;
            var end = text.IndexOf(pair.Item2, start + 1);
            if (end > start) return text[(start + 1)..end].Trim();
        }

        return string.Empty;
    }

    private static string ExtractAfterAny(string text, params string[] markers)
    {
        foreach (var marker in markers)
        {
            var index = text.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
            if (index < 0) continue;
            var tail = text[(index + marker.Length)..].Trim(' ', ':', '-', ',', ';');
            if (tail.Length == 0) continue;
            var stop = tail.IndexOfAny([';', '\r', '\n']);
            return stop > 0 ? tail[..stop].Trim() : tail.Trim();
        }

        return string.Empty;
    }

    private static string FirstNonEmpty(params string?[] values)
        => values.FirstOrDefault(value => !string.IsNullOrWhiteSpace(value))?.Trim() ?? string.Empty;

    private static string TrimGbk(string value, int maxBytes)
    {
        if (maxBytes <= 0) return string.Empty;
        value = value.Trim();
        if (EncodingService.GetGbkByteCount(value) <= maxBytes) return value;
        var builder = new StringBuilder();
        foreach (var ch in value)
        {
            var next = builder.ToString() + ch;
            if (EncodingService.GetGbkByteCount(next) > maxBytes) break;
            builder.Append(ch);
        }

        return builder.ToString();
    }

    private static string Tail(string value, int maxChars)
        => value.Length <= maxChars ? value : value[^maxChars..];
}
