using System.Data;
using System.Globalization;
using System.Text.Json;
using CCZModStudio.Formats;
using CCZModStudio.Models;

namespace CCZModStudio.Core;

public sealed partial class ModPackageService
{
    public StandaloneScenarioAnalysisResult AnalyzeStandaloneScenarioRequest(
        CczProject project,
        string prompt,
        string? title = null,
        string? packageId = null)
    {
        prompt = string.IsNullOrWhiteSpace(prompt) ? "Create a standalone CCZ 6.5 single-stage scenario." : prompt.Trim();
        var inferredTitle = TrimGbk(FirstNonEmpty(title, ExtractStandaloneTitle(prompt), ExtractQuoted(prompt), ExtractAfterAny(prompt, "title", "name"), "Standalone Stage"), 16);
        var theme = InferStandaloneTheme(prompt);
        var design = new StandaloneScenarioDesign
        {
            DesignId = MakeSafeFileStem(FirstNonEmpty(packageId, inferredTitle, "standalone-stage")),
            SourcePrompt = prompt,
            Title = inferredTitle,
            Theme = theme,
            TargetVersion = "6.5",
            Synopsis = TrimGbk(FirstNonEmpty(ExtractAfterAny(prompt, "story", "synopsis"), $"A complete standalone {theme} stage with intro, deployment, battle events, victory, defeat, and epilogue."), 180),
            RScenarioId = "R_AUTO",
            SScenarioId = "S_AUTO",
            Rewards = { "Bonus gold", "Rare item", "Story unlock" },
            Assumptions =
            {
                ["scope"] = "standalone_single_stage",
                ["constraint_mode"] = "force_open",
                ["rs_event_dsl"] = "typed_event_graph",
                ["write_policy"] = "Structure commands are generated for preview/report; direct writes still require preview."
            }
        };

        AddStandaloneRoles(design);
        AddStandaloneBattlePlan(design, prompt);
        AddStandaloneEventGraph(design);
        AddStandaloneResourcePlan(design);

        return new StandaloneScenarioAnalysisResult
        {
            ProjectRoot = project.GameRoot,
            Design = design,
            Decisions =
            {
                "Expanded prompt into a standalone R+S design.",
                "Applied force_open constraints for complete single-stage output.",
                "Generated default roles, battle deployment, event graph, rewards, and resource needs."
            }
        };
    }

    public StandaloneScenarioCompileResult CompileStandaloneScenarioPackage(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        StandaloneScenarioDesign design,
        int slotLimit = 64)
    {
        ArgumentNullException.ThrowIfNull(design);
        if (design.Roles.Count == 0) AddStandaloneRoles(design);
        if (design.Battle.Units.Count == 0) AddStandaloneBattlePlan(design, design.SourcePrompt);
        if (design.EventGraph.Nodes.Count == 0) AddStandaloneEventGraph(design);
        if (design.Resources.Needs.Count == 0) AddStandaloneResourcePlan(design);

        var slots = ListAvailableSlots(project, tables, slotLimit);
        BindStandaloneSlots(slots, design);
        var packageId = MakeSafeFileStem(FirstNonEmpty(design.DesignId, design.Title, "standalone-stage"));
        var package = new ModPackage
        {
            Metadata = new ModPackageMetadata
            {
                PackageId = packageId,
                Name = FirstNonEmpty(design.Title, "Standalone Stage"),
                Theme = FirstNonEmpty(design.Theme, "Classic CCZ"),
                TargetVersion = FirstNonEmpty(design.TargetVersion, "6.5"),
                AuthorNote = "Generated by compile_standalone_scenario_package.",
                SourcePrompt = design.SourcePrompt,
                Tags =
                {
                    ["scope"] = "standalone_single_stage",
                    ["constraint_mode"] = "force_open"
                }
            },
            ValidationPlan = new ModValidationPlan
            {
                RequirePreview = true,
                RequireTestCopy = false,
                RequireReread = true,
                RequireRuntimeSmoke = true,
                SmokeCommands =
                {
                    "--standalone-scenario-smoke",
                    "--standalone-semantic-smoke",
                    "--standalone-golden-samples-smoke",
                    "--mod-package-smoke",
                    "--rs-text-write-smoke",
                    "--rs-deployment-write-smoke",
                    "--rs-write-smoke",
                    "--hexzmap-sync-smoke",
                    "--map-terrain-consistency-smoke",
                    "--strict-playable-preview-smoke"
                },
                ManualChecks =
                {
                    "Playability: R intro can open.",
                    "Playability: R intro contains an S jump plan.",
                    "Playability: S battle has deployment, victory, defeat, battle events, and epilogue.",
                    "Force-open: validation failures are reported but do not reduce output to text-only."
                }
            }
        };

        package.SlotPlan.PersonIds.AddRange(design.Roles.Select(role => role.PersonId).Where(id => id > 0));
        package.SlotPlan.JobIds.AddRange(design.Roles.Select(role => role.JobId).Where(id => id > 0).Distinct());
        package.SlotPlan.ItemIds.AddRange(PickIds(slots, "item", 2));
        package.SlotPlan.EffectIds.AddRange(PickIds(slots, "item_effect", 2));
        package.SlotPlan.FaceImageNumbers.AddRange(design.Roles.Select(role => role.FaceImageNumber).Where(id => id > 0));
        package.SlotPlan.RImageIds.AddRange(design.Roles.Select(role => role.RImageId).Where(id => id > 0));
        package.SlotPlan.SImageIds.AddRange(design.Roles.Select(role => role.SImageId).Where(id => id > 0));
        package.SlotPlan.ScenarioIds.Add(FirstNonEmpty(design.RScenarioId, "R_AUTO"));
        package.SlotPlan.ScenarioIds.Add(FirstNonEmpty(design.SScenarioId, "S_AUTO"));
        package.SlotPlan.MapIds.Add(FirstNonEmpty(design.Battle.MapId, "M000"));
        package.SlotPlan.Notes["standalone_title"] = design.Title;
        package.SlotPlan.Notes["event_nodes"] = design.EventGraph.Nodes.Count.ToString(CultureInfo.InvariantCulture);
        package.SlotPlan.Notes["deployment_units"] = design.Battle.Units.Count.ToString(CultureInfo.InvariantCulture);
        package.SlotPlan.Notes["resource_needs"] = string.Join("; ", design.Resources.Needs.Select(need => $"{need.Kind}:{need.Target}"));

        AddStandaloneTableUpdates(project, tables, package, design);
        AddStandaloneEffectPackages(package, design);
        AddStandaloneScenarioPatches(project, package, design);
        AddStandaloneResourcePlans(package, design);

        var playability = BuildStandalonePlayabilityChecklist(design, package);
        return new StandaloneScenarioCompileResult
        {
            ProjectRoot = project.GameRoot,
            Design = design,
            Slots = slots,
            Package = package,
            Playability = playability,
            Decisions =
            {
                $"roles: {design.Roles.Count}",
                $"deployment units: {design.Battle.Units.Count}",
                $"event nodes: {design.EventGraph.Nodes.Count}",
                $"R/S: {string.Join(", ", package.SlotPlan.ScenarioIds)}",
                "force_open keeps structural scenario output visible for preview/report."
            }
        };
    }

    private static void AddStandaloneRoles(StandaloneScenarioDesign design)
    {
        if (design.Roles.Count > 0) return;
        var names = ExtractStandaloneRoleNames(design.SourcePrompt);
        var defaults = new[] { "Hero", "Strategist", "Archer", "Medic", "Guest", "Boss", "Enemy1", "Enemy2", "Enemy3", "Enemy4", "Enemy5", "Enemy6", "Enemy7", "Enemy8" };
        while (names.Count < defaults.Length) names.Add(defaults[names.Count]);
        var jobs = new[] { "Commander", "Strategist", "Archer", "Medic", "Guest", "Boss", "Guard", "Archer", "Tactician", "Cavalry", "Infantry", "Mage", "Captain", "Guard" };
        var factions = InferStandaloneFactions(design.SourcePrompt, names.Count);
        for (var i = 0; i < 14; i++)
        {
            design.Roles.Add(new StandaloneScenarioRole
            {
                Key = i switch
                {
                    0 => "hero",
                    1 => "strategist",
                    2 => "archer",
                    3 => "healer",
                    4 => "guest",
                    5 => "boss",
                    _ => "enemy" + (i - 5).ToString(CultureInfo.InvariantCulture)
                },
                Name = TrimGbk(names[i], 16),
                Faction = i < factions.Count ? factions[i] : i < 4 ? "ally" : i == 4 ? "friendly" : "enemy",
                Job = jobs[i],
                Personality = i switch
                {
                    0 => "bold",
                    1 => "calm",
                    2 => "precise",
                    3 => "careful",
                    4 => "loyal",
                    5 => "proud",
                    _ => "disciplined"
                },
                GameplayRole = i switch
                {
                    0 => "frontline leader",
                    1 => "support strategist",
                    2 => "ranged pressure",
                    3 => "healer",
                    4 => "guest ally",
                    5 => "enemy commander",
                    _ => "enemy unit"
                },
                Level = i < 4 ? 12 : i == 4 ? 10 : i == 5 ? 16 : 11
            });
        }
    }

    private static void AddStandaloneBattlePlan(StandaloneScenarioDesign design, string prompt)
    {
        design.Battle.MapTheme = InferStandaloneMapTheme(prompt);
        design.Battle.MapId = InferStandaloneMapId(prompt);
        design.Battle.Objective = FirstNonEmpty(ExtractAfterAny(prompt, "objective", "win", "目标", "胜利"), InferStandaloneObjective(prompt));
        design.Battle.Tempo = prompt.Contains("fast", StringComparison.OrdinalIgnoreCase) ? "fast pressure" : "steady advance";
        design.Battle.TurnLimit = prompt.Contains("fast", StringComparison.OrdinalIgnoreCase) ? 18 : 24;
        design.Battle.WinConditions.AddRange(new[] { design.Battle.Objective, "At least one allied unit survives." });
        design.Battle.LoseConditions.AddRange(InferStandaloneLoseConditions(prompt));

        var coordinates = new (int X, int Y, int Direction)[]
        {
            (6, 18, 0), (5, 19, 0), (7, 19, 0), (6, 20, 0), (8, 18, 3),
            (6, 5, 2), (4, 7, 2), (8, 7, 2), (3, 9, 2), (9, 9, 2), (5, 11, 2), (7, 11, 2), (4, 13, 2), (8, 13, 2)
        };
        for (var i = 0; i < design.Roles.Count && i < coordinates.Length; i++)
        {
            var role = design.Roles[i];
            var side = role.Faction == "ally" ? "ally" : role.Faction == "friendly" ? "friendly" : "enemy";
            design.Battle.Units.Add(new BattleDeploymentUnit
            {
                RoleKey = role.Key,
                Side = side,
                X = coordinates[i].X,
                Y = coordinates[i].Y,
                Direction = coordinates[i].Direction,
                AiPolicy = side == "enemy" ? 2 : 0,
                LevelBonus = role.Level
            });
        }
    }

    private static void AddStandaloneEventGraph(StandaloneScenarioDesign design)
    {
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "intro",
            Kind = "intro",
            Trigger = "r_start",
            Title = "Opening",
            Actions =
            {
                Dialog("hero", $"{design.Title}: {design.Synopsis}"),
                Dialog("strategist", "The enemy formation is set. Hold the center before pushing forward."),
                Dialog("hero", "Advance as one. We finish this today.")
            },
            Next = { "deploy" }
        });
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "deploy",
            Kind = "deploy",
            Trigger = "s_start",
            Title = "Deployment",
            Actions =
            {
                Text("Objective: " + design.Battle.Objective),
                Text("Enemy pressure rises on turn three.")
            },
            Next = { "turn_start_3", "boss_talk" }
        });
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "turn_start_3",
            Kind = "turn_start",
            Trigger = "turn=3",
            Title = "Enemy Push",
            Actions =
            {
                Dialog("boss", "Break their line before they regroup."),
                Text("Enemy front line advances.")
            },
            Next = { "area_entered" }
        });
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "area_entered",
            Kind = "area_entered",
            Trigger = "hero x=6 y<=10",
            Title = "Flank",
            Actions =
            {
                Dialog("guest", "I will hold their flank. Strike the commander."),
                Text("Friendly unit pins the enemy wing.")
            },
            Next = { "boss_talk" }
        });
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "boss_talk",
            Kind = "unit_defeated",
            Trigger = "boss hp<=50%",
            Title = "Commander",
            Actions =
            {
                Dialog("boss", "You think this is enough to move my banner?"),
                Dialog("hero", "Your line is broken. Stand down.")
            },
            Next = { "victory", "defeat" }
        });
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "victory",
            Kind = "victory",
            Trigger = "boss_defeated",
            Title = "Victory",
            Actions =
            {
                Text("Victory conditions met."),
                Dialog("strategist", "The enemy has scattered. We have the field.")
            },
            Next = { "epilogue" }
        });
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "defeat",
            Kind = "defeat",
            Trigger = "hero_retreat_or_turn_limit",
            Title = "Defeat",
            Actions =
            {
                Text("Defeat conditions met."),
                Dialog("hero", "Fall back and preserve the army.")
            }
        });
        design.EventGraph.Nodes.Add(new ScenarioEventNode
        {
            Id = "epilogue",
            Kind = "epilogue",
            Trigger = "after_victory",
            Title = "Epilogue",
            Actions =
            {
                Dialog("hero", "This battle is only the beginning."),
                Text("Rewards: " + string.Join("; ", design.Rewards))
            }
        });
    }

    private static void AddStandaloneResourcePlan(StandaloneScenarioDesign design)
    {
        design.Resources.Style = "classic CCZ 6.5 pixel-compatible assets";
        foreach (var role in design.Roles.Take(6))
        {
            design.Resources.Needs.Add(new ScenarioResourceNeed { Kind = "face", Target = role.Name, Description = role.Name + " portrait" });
            design.Resources.Needs.Add(new ScenarioResourceNeed { Kind = "r_actor", Target = role.Name, Description = role.Name + " R actor" });
            design.Resources.Needs.Add(new ScenarioResourceNeed { Kind = "s_unit", Target = role.Name, Description = role.Name + " S unit" });
        }

        foreach (var need in design.Resources.Needs)
        {
            need.PlaceholderAllowed = false;
        }

        design.Resources.Needs.Add(new ScenarioResourceNeed { Kind = "map", Target = design.Battle.MapId, Description = design.Battle.MapTheme + " map", PlaceholderAllowed = false });
        design.Resources.Needs.Add(new ScenarioResourceNeed { Kind = "icon", Target = design.Title, Description = design.Title + " icon", PlaceholderAllowed = false });
    }

    private static ScenarioEventAction Dialog(string actorKey, string text)
        => new() { Kind = "dialog", ActorKey = actorKey, Text = text };

    private static ScenarioEventAction Text(string text)
        => new() { Kind = "text", Text = text };

    private static void BindStandaloneSlots(ModAvailableSlotsResult slots, StandaloneScenarioDesign design)
    {
        var personIds = PickIds(slots, "person", design.Roles.Count);
        var jobIds = PickIds(slots, "job_detail", Math.Min(design.Roles.Count, 8));
        var faceIds = PickImageIds(slots, "Face", design.Roles.Count);
        var rImages = PickImageIds(slots, "Pmapobj", design.Roles.Count).Select(id => Math.Max(0, (id - 1) / 2)).Distinct().ToList();
        var sImages = PickImageIds(slots, "Unit_mov", design.Roles.Count);
        for (var i = 0; i < design.Roles.Count; i++)
        {
            var role = design.Roles[i];
            if (i < personIds.Count) role.PersonId = personIds[i];
            if (jobIds.Count > 0) role.JobId = jobIds[Math.Min(i, jobIds.Count - 1)];
            if (i < faceIds.Count) role.FaceImageNumber = faceIds[i];
            if (i < rImages.Count) role.RImageId = rImages[i];
            if (i < sImages.Count) role.SImageId = sImages[i];
        }

        design.RScenarioId = FirstNonEmpty(PickKeys(slots, "r_scenario", 1).FirstOrDefault(), design.RScenarioId, "R_AUTO");
        design.SScenarioId = FirstNonEmpty(PickKeys(slots, "s_scenario", 1).FirstOrDefault(), design.SScenarioId, "S_AUTO");
    }

    private void AddStandaloneTableUpdates(
        CczProject project,
        IReadOnlyList<HexTableDefinition> tables,
        ModPackage package,
        StandaloneScenarioDesign design)
    {
        var modRoles = design.Roles.Select(role => new ModDesignRole
        {
            Name = role.Name,
            Faction = role.Faction,
            Job = role.Job,
            Personality = role.Personality,
            GameplayRole = role.GameplayRole
        }).ToList();
        var engine = _engineProfiles.Detect(project);
        AddRoleTableUpdates(project, tables, package, engine.TableHints.PersonTable, modRoles, design.Roles.Select(role => role.PersonId).Where(id => id > 0).ToList());
        AddJobTableUpdates(project, tables, package, engine.TableHints.DetailedJobTable, modRoles, design.Roles.Select(role => role.JobId).Where(id => id > 0).Distinct().ToList());
    }

    private static void AddStandaloneEffectPackages(ModPackage package, StandaloneScenarioDesign design)
    {
        if (package.SlotPlan.EffectIds.Count == 0 || package.SlotPlan.ItemIds.Count == 0) return;
        var effectId = package.SlotPlan.EffectIds[0];
        var itemId = package.SlotPlan.ItemIds[0];
        package.EffectPackages.Add(new EffectPackage
        {
            PackageId = package.Metadata.PackageId + "-standalone-effect",
            Domain = "item",
            EffectId = effectId,
            Name = TrimGbk("Stage Reward", 16),
            Description = TrimGbk("Standalone stage generated effect.", 64),
            EffectValue = 8,
            Bindings =
            {
                new EffectPackageBinding { Kind = "item", RowId = itemId, ItemId = itemId, EffectValue = 8, Note = "Standalone generated effect." }
            },
            SourcePrompt = design.SourcePrompt,
            BackupNote = "Standalone scenario effect."
        });
    }

    private static void AddStandaloneScenarioPatches(CczProject project, ModPackage package, StandaloneScenarioDesign design)
    {
        var rsRoot = Path.Combine(project.GameRoot, "RS");
        var rPath = ExistingScenarioPath(rsRoot, "R") ?? Path.Combine("RS", FirstNonEmpty(design.RScenarioId, "R_AUTO") + ".eex");
        var sPath = ExistingScenarioPath(rsRoot, "S") ?? Path.Combine("RS", FirstNonEmpty(design.SScenarioId, "S_AUTO") + ".eex");
        package.ScenarioPatches.Add(BuildStandaloneRScenarioPatch(package, design, rPath));
        package.ScenarioPatches.Add(BuildStandaloneSScenarioPatch(package, design, sPath));
    }

    private static ModScenarioPatch BuildStandaloneRScenarioPatch(ModPackage package, StandaloneScenarioDesign design, string relativePath)
    {
        var commands = new List<ModScenarioCommandDraft>
        {
            TextCommand(0x14, "[" + design.Title + "] " + design.Synopsis)
        };
        foreach (var node in design.EventGraph.Nodes.Where(node => node.Kind is "intro" or "epilogue"))
        {
            commands.Add(TextCommand(0x14, "[" + node.Title + "]"));
            commands.AddRange(node.Actions.Select(BuildScenarioActionCommand));
        }

        commands.Add(TextCommand(0x19, "Objective: " + design.Battle.Objective));
        commands.Add(Command(0x11, Word(ParseScenarioNumber(design.SScenarioId)), Word(0)));
        commands[^1].Note = "typed_event:jump_to_battle target=" + design.SScenarioId;
        return new ModScenarioPatch
        {
            PatchId = package.Metadata.PackageId + "-standalone-r",
            RelativePath = relativePath,
            Note = "Standalone R event graph.",
            Operations =
            {
                new ModScenarioPatchOperation
                {
                    Operation = "append_command",
                    SceneIndex = 1,
                    SectionIndex = 1,
                    Commands = commands,
                    Note = "force_open standalone R event graph."
                }
            }
        };
    }

    private static ModScenarioPatch BuildStandaloneSScenarioPatch(ModPackage package, StandaloneScenarioDesign design, string relativePath)
    {
        var commands = new List<ModScenarioCommandDraft>
        {
            TextCommand(0x14, "Battle objective: " + design.Battle.Objective),
            TextCommand(0x19, "Win: " + string.Join("; ", design.Battle.WinConditions)),
            TextCommand(0x1A, "Lose: " + string.Join("; ", design.Battle.LoseConditions)),
            BuildDeploymentCommand(0x44, design.Battle.Units.Where(unit => unit.Side == "ally"), design),
            BuildDeploymentCommand(0x46, design.Battle.Units.Where(unit => unit.Side == "friendly"), design),
            BuildDeploymentCommand(0x47, design.Battle.Units.Where(unit => unit.Side == "enemy"), design)
        };

        foreach (var node in design.EventGraph.Nodes.Where(node => node.Kind is not "intro" and not "epilogue"))
        {
            commands.Add(BuildScenarioEventTriggerCommand(node, design));
            commands[^1].Note = "typed_event:" + node.Kind + " id=" + node.Id + " trigger=" + node.Trigger;
            commands.AddRange(node.Actions.Select(BuildScenarioActionCommand));
        }

        commands.Add(BuildRewardCommand(design));
        commands.Add(TextCommand(0x14, "Rewards: " + string.Join("; ", design.Rewards)));
        return new ModScenarioPatch
        {
            PatchId = package.Metadata.PackageId + "-standalone-s",
            RelativePath = relativePath,
            Note = "Standalone S battle graph.",
            Operations =
            {
                new ModScenarioPatchOperation
                {
                    Operation = "append_command",
                    SceneIndex = 1,
                    SectionIndex = 1,
                    Commands = commands,
                    Note = "force_open standalone S event graph."
                }
            }
        };
    }

    private static ModScenarioCommandDraft BuildDeploymentCommand(int commandId, IEnumerable<BattleDeploymentUnit> units, StandaloneScenarioDesign design)
    {
        var parameters = new List<ModScenarioParameterDraft>();
        foreach (var unit in units)
        {
            var role = RoleByKey(design, unit.RoleKey);
            parameters.Add(Word(role.PersonId));
            parameters.Add(Word(role.JobId));
            parameters.Add(Word(unit.X));
            parameters.Add(Word(unit.Y));
            parameters.Add(Word(unit.Direction));
            parameters.Add(Word(unit.AiPolicy));
            parameters.Add(Word(role.Level));
            parameters.Add(Word(0));
            parameters.Add(Word(0));
            parameters.Add(Word(0));
            parameters.Add(Word(role.SImageId));
            if (commandId == 0x47) parameters.Add(Word(0));
        }

        var draft = Command(commandId, parameters.ToArray());
        draft.Note = "deployment command " + HexDisplayFormatter.FormatByte((byte)commandId);
        return draft;
    }

    private static ModScenarioCommandDraft BuildScenarioActionCommand(ScenarioEventAction action)
    {
        if (action.Kind.Equals("appear", StringComparison.OrdinalIgnoreCase))
        {
            return Command(0x30, Word(action.Value), Dword(action.X), Dword(action.Y), Word(action.Direction), Word(action.ActionId));
        }

        return TextCommand(0x14, action.Text);
    }

    private static ModScenarioCommandDraft BuildScenarioEventTriggerCommand(ScenarioEventNode node, StandaloneScenarioDesign design)
    {
        var draft = node.Kind.ToLowerInvariant() switch
        {
            "deploy" => Command(0x5A),
            "turn_start" => Command(0x77, Word(ParseFirstInteger(node.Trigger, 1)), Word(0)),
            "area_entered" => Command(0x12, Word(ParseFirstInteger(node.Trigger, 0)), Word(ParseLastInteger(node.Trigger, 0))),
            "unit_defeated" => Command(0x13, Word(RoleByKey(design, "boss").PersonId)),
            "victory" => Command(0x11, Word(ParseScenarioNumber(design.RScenarioId)), Word(1)),
            "defeat" => Command(0x11, Word(ParseScenarioNumber(design.RScenarioId)), Word(2)),
            _ => Command(0x76, Word(0))
        };
        draft.Note = "typed_event:" + node.Kind + ":" + node.Id + ":" + node.Trigger;
        return draft;
    }

    private static ModScenarioCommandDraft BuildRewardCommand(StandaloneScenarioDesign design)
    {
        var draft = Command(0x72, Word(10), Word(design.Rewards.Count));
        draft.Note = "typed_event:reward:" + string.Join("/", design.Rewards);
        return draft;
    }

    private static StandaloneScenarioRole RoleByKey(StandaloneScenarioDesign design, string key)
        => design.Roles.FirstOrDefault(role => role.Key.Equals(key, StringComparison.OrdinalIgnoreCase))
           ?? design.Roles.First();

    private static void AddStandaloneResourcePlans(ModPackage package, StandaloneScenarioDesign design)
    {
        package.SlotPlan.Notes["resource_style"] = design.Resources.Style;
        foreach (var need in design.Resources.Needs)
        {
            package.SlotPlan.Notes["resource:" + need.Kind + ":" + need.Target] = need.Description;
            package.ResourceUpdates.Add(new ModResourceUpdate
            {
                Kind = need.Kind,
                TargetRelativePath = need.Target,
                Operation = "generate_task",
                Note = need.Description + (need.PlaceholderAllowed ? "; placeholder allowed" : "; final asset required")
            });
        }
    }

    private static StandaloneScenarioPlayabilityChecklist BuildStandalonePlayabilityChecklist(StandaloneScenarioDesign design, ModPackage package)
    {
        var checklist = new StandaloneScenarioPlayabilityChecklist
        {
            HasRIntro = design.EventGraph.Nodes.Any(node => node.Kind == "intro"),
            HasRToSJump = package.ScenarioPatches.Any(patch => patch.PatchId.Contains("-r", StringComparison.OrdinalIgnoreCase)),
            HasBattleDeployment = design.Battle.Units.Count >= 10,
            HasVictoryCondition = design.EventGraph.Nodes.Any(node => node.Kind == "victory") && design.Battle.WinConditions.Count > 0,
            HasDefeatCondition = design.EventGraph.Nodes.Any(node => node.Kind == "defeat") && design.Battle.LoseConditions.Count > 0,
            HasBattleEvents = design.EventGraph.Nodes.Count(node => node.Kind is "turn_start" or "unit_defeated" or "area_entered") >= 2,
            HasEpilogue = design.EventGraph.Nodes.Any(node => node.Kind == "epilogue")
        };

        if (!checklist.HasRToSJump) checklist.Risks.Add("R script lacks an S route plan.");
        if (!checklist.HasBattleDeployment) checklist.Risks.Add("S battle deployment is too small.");
        if (!checklist.HasVictoryCondition) checklist.Risks.Add("Missing victory condition.");
        if (!checklist.HasDefeatCondition) checklist.Risks.Add("Missing defeat condition.");
        if (!checklist.HasBattleEvents) checklist.Risks.Add("Too few battle events.");
        if (!checklist.HasEpilogue) checklist.Risks.Add("Missing epilogue.");
        return checklist;
    }

    private static string ExtractStandaloneTitle(string prompt)
    {
        foreach (var marker in new[] { "MOD：", "MOD:", "独立单关：", "独立单关:", "标题：", "标题:" })
        {
            var index = prompt.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
            if (index < 0) continue;
            var tail = prompt[(index + marker.Length)..].Trim();
            var stop = tail.IndexOfAny(['。', '；', ';', '\r', '\n']);
            var title = stop > 0 ? tail[..stop].Trim() : tail.Trim();
            if (!string.IsNullOrWhiteSpace(title)) return title;
        }

        return string.Empty;
    }

    private static string InferStandaloneTheme(string prompt)
    {
        if (ContainsAny(prompt, "北邙", "祭坛", "血祭", "魔阵")) return "北邙山祭坛决战";
        if (ContainsAny(prompt, "山", "山道", "山林", "隘口")) return "山地决战";
        if (ContainsAny(prompt, "水战", "江", "河", "海", "船")) return "水战奇袭";
        if (ContainsAny(prompt, "城", "关隘", "城门")) return "城池攻防";
        return InferTheme(prompt);
    }

    private static string InferStandaloneMapTheme(string prompt)
    {
        if (ContainsAny(prompt, "北邙", "祭坛", "血祭")) return "北邙山祭坛";
        if (ContainsAny(prompt, "水战", "江", "河", "海", "船")) return "river crossing";
        if (ContainsAny(prompt, "山", "山道", "山林", "隘口")) return "mountain pass";
        if (ContainsAny(prompt, "城", "城门")) return "city gate";
        return InferMapTheme(prompt);
    }

    private static string InferStandaloneMapId(string prompt)
    {
        var mapIndex = prompt.IndexOf("Map/M", StringComparison.OrdinalIgnoreCase);
        if (mapIndex >= 0 && prompt.Length >= mapIndex + 8)
        {
            var id = new string(prompt[(mapIndex + 4)..].TakeWhile(ch => char.IsLetterOrDigit(ch)).ToArray());
            if (!string.IsNullOrWhiteSpace(id)) return id.ToUpperInvariant();
        }

        var mIndex = prompt.IndexOf("M003", StringComparison.OrdinalIgnoreCase);
        if (mIndex >= 0) return "M003";
        return "M000";
    }

    private static string InferStandaloneObjective(string prompt)
    {
        if (ContainsAny(prompt, "龙帝")) return "击破龙帝并阻止血祭";
        return "Defeat the enemy commander.";
    }

    private static IReadOnlyList<string> InferStandaloneLoseConditions(string prompt)
    {
        var result = new List<string>();
        var loseText = ExtractAfterAny(prompt, "失败条件", "lose");
        if (!string.IsNullOrWhiteSpace(loseText))
        {
            result.AddRange(loseText.Split(['；', ';', '，', ','], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries));
        }

        if (result.Count == 0 && ContainsAny(prompt, "岳夜", "襄慎", "刘生"))
        {
            result.Add("岳夜、襄慎、刘生任一阵亡");
        }

        if (result.Count == 0) result.Add("Hero retreats.");
        result.Add("Turn limit expires.");
        return result;
    }

    private static List<string> ExtractStandaloneRoleNames(string prompt)
    {
        var result = new List<string>();
        var roleBlock = ExtractSection(prompt, ["角色：", "角色:", "characters:", "roles:"], ["要求：", "要求:", "地图：", "地图:", "目标：", "胜利条件", "\n\n"]);
        if (!string.IsNullOrWhiteSpace(roleBlock))
        {
            foreach (var part in roleBlock.Split(['；', ';'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var namePart = part.Split(['，', ',', '：', ':'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).FirstOrDefault() ?? string.Empty;
                var cleaned = CleanStandaloneName(namePart);
                if (IsStandaloneName(cleaned) && !result.Contains(cleaned, StringComparer.OrdinalIgnoreCase))
                {
                    result.Add(cleaned);
                }
            }
        }

        if (result.Count == 0)
        {
            result.AddRange(ExtractNames(prompt).Where(name => !LooksLikeRoleDescription(name)));
        }

        if (ContainsAny(prompt, "三英战", "龙帝"))
        {
            foreach (var name in new[] { "岳夜", "襄慎", "刘生", "新岳亲卫", "北邙义民", "龙帝" })
            {
                if (prompt.Contains(name, StringComparison.Ordinal) && !result.Contains(name, StringComparer.OrdinalIgnoreCase))
                {
                    result.Add(name);
                }
            }
        }

        return result.Take(14).ToList();
    }

    private static List<string> InferStandaloneFactions(string prompt, int roleCount)
    {
        var result = Enumerable.Repeat("enemy", Math.Max(roleCount, 14)).ToList();
        var allyCount = ParseCountBefore(prompt, "名我方", 4);
        var friendlyCount = ParseCountBefore(prompt, "名友军", 1);
        for (var i = 0; i < Math.Min(allyCount, result.Count); i++) result[i] = "ally";
        for (var i = allyCount; i < Math.Min(allyCount + friendlyCount, result.Count); i++) result[i] = "friendly";
        return result;
    }

    private static string ExtractSection(string text, string[] starts, string[] stops)
    {
        var start = starts
            .Select(marker => new { Marker = marker, Index = text.IndexOf(marker, StringComparison.OrdinalIgnoreCase) })
            .Where(item => item.Index >= 0)
            .OrderBy(item => item.Index)
            .FirstOrDefault();
        if (start == null) return string.Empty;

        var sectionStart = start.Index + start.Marker.Length;
        var tail = text[sectionStart..];
        var stop = stops
            .Select(marker => tail.IndexOf(marker, StringComparison.OrdinalIgnoreCase))
            .Where(index => index >= 0)
            .DefaultIfEmpty(tail.Length)
            .Min();
        return tail[..stop].Trim();
    }

    private static string CleanStandaloneName(string value)
    {
        var cleaned = new string(value.Trim().Where(ch => char.IsLetterOrDigit(ch) || ch >= 0x4E00 && ch <= 0x9FFF).ToArray());
        return cleaned.Trim();
    }

    private static bool IsStandaloneName(string value)
        => value.Length is >= 2 and <= 16 && !LooksLikeRoleDescription(value);

    private static bool LooksLikeRoleDescription(string value)
        => ContainsAny(value, "山贼王者", "虎啸山林", "智勇双全", "海上锦帆", "剽掠四方", "少林扫地僧", "手持", "残暴", "嗜血");

    private static bool ContainsAny(string value, params string[] terms)
        => terms.Any(term => value.Contains(term, StringComparison.OrdinalIgnoreCase));

    private static int ParseCountBefore(string text, string marker, int fallback)
    {
        var index = text.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
        if (index <= 0) return fallback;
        var digits = new string(text[..index].Reverse().TakeWhile(char.IsDigit).Reverse().ToArray());
        return int.TryParse(digits, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value) ? value : fallback;
    }

    private static int ParseScenarioNumber(string scenarioId)
    {
        var digits = new string((scenarioId ?? string.Empty).Where(char.IsDigit).ToArray());
        return int.TryParse(digits, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value) ? value : 0;
    }

    private static int ParseFirstInteger(string text, int fallback)
    {
        var digits = new string((text ?? string.Empty).SkipWhile(ch => !char.IsDigit(ch)).TakeWhile(char.IsDigit).ToArray());
        return int.TryParse(digits, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value) ? value : fallback;
    }

    private static int ParseLastInteger(string text, int fallback)
    {
        var groups = new List<string>();
        var current = new List<char>();
        foreach (var ch in text ?? string.Empty)
        {
            if (char.IsDigit(ch))
            {
                current.Add(ch);
            }
            else if (current.Count > 0)
            {
                groups.Add(new string(current.ToArray()));
                current.Clear();
            }
        }

        if (current.Count > 0) groups.Add(new string(current.ToArray()));
        return groups.Count > 0 && int.TryParse(groups[^1], NumberStyles.Integer, CultureInfo.InvariantCulture, out var value) ? value : fallback;
    }

    private static ModScenarioCommandDraft Command(int commandId, params ModScenarioParameterDraft[] parameters)
        => new()
        {
            CommandId = commandId,
            Parameters = parameters.ToList()
        };

    private static ModScenarioParameterDraft Word(int value)
        => new() { Kind = "word16", LayoutCode = 0x02, IntValue = value };

    private static ModScenarioParameterDraft Dword(int value)
        => new() { Kind = "dword32", LayoutCode = 0x03, IntValue = value };
}
